name: todo
description: Todo App.

publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  cloud_firestore: ^0.16.0
  cupertino_icons: ^1.0.0
  firebase_core: ^0.7.0
  flutter_hooks: ^0.15.0
  hive: ^1.4.4+1
  hooks_riverpod: ^0.12.4
  image_picker: ^0.6.7+22
  intl: ^0.16.0
  path_provider: ^1.6.27

dev_dependencies:
  flutter_test:
    sdk: flutter
  build_runner: ^1.10.13
  hive_generator: ^0.8.2

flutter:
  uses-material-design: true

  assets:
    - assets/images/

  fonts:
    - family: Montserrat
      fonts:
        - asset: assets/fonts/Montserrat-Regular.ttf
        - asset: assets/fonts/Montserrat-Bold.ttf
          weight: 700
